name = "fluid-forge"
version = "0.0.1"
license = "GNU GPL v3"
author = "Trevor Crawford"
maintainer = "crawford.trevor@gmail.com"
copyright = "Copyright 2025, Trevor Crawford"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

